# RT-Thread building script for component
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
main.c
test.c
GUI.c
lcd.c
ILI93xx.c
24cxx.c
touch.c
myiic.c
key.c
""")

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
